// Generated by Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import CoreLocation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ProximitisFramework",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class UIColor;

SWIFT_PROTOCOL("_TtP19ProximitisFramework14FontProperties_")
@protocol FontProperties
@property (nonatomic, copy) NSString * _Nullable fontName;
@property (nonatomic, strong) UIColor * _Nonnull color;
@property (nonatomic) CGFloat fontSize;
@end


/// A struct defining the styles that can be applied to the parsed Markdown. The <code>fontName</code> property is optional, and if it’s not set then the <code>fontName</code> property of the Body style will be applied.
/// If that is not set, then the system default will be used.
SWIFT_CLASS("_TtC19ProximitisFramework11BasicStyles")
@interface BasicStyles : NSObject <FontProperties>
@property (nonatomic, copy) NSString * _Nullable fontName;
@property (nonatomic, strong) UIColor * _Nonnull color;
@property (nonatomic) CGFloat fontSize;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19ProximitisFramework13DefaultObject")
@interface DefaultObject : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * _Nonnull id;
@end

@class NSCoder;

SWIFT_CLASS("_TtC19ProximitisFramework6Beacon")
@interface Beacon : DefaultObject <NSCoding>
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (BOOL)isAllowedToUpdate SWIFT_WARN_UNUSED_RESULT;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19ProximitisFramework13BeaconFactory")
@interface BeaconFactory : NSObject
+ (BeaconFactory * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (Beacon * _Nullable)findBeaconWithNamespace:(NSString * _Nonnull)namespace_ instance:(NSString * _Nonnull)instance create:(BOOL)create SWIFT_WARN_UNUSED_RESULT;
- (void)setUpdateWithBeacon:(Beacon * _Nonnull)beacon;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19ProximitisFramework13BeaconManager")
@interface BeaconManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CLLocationManager;
@class CLRegion;

@interface BeaconManager (SWIFT_EXTENSION(ProximitisFramework)) <CLLocationManagerDelegate>
- (void)locationManager:(CLLocationManager * _Nonnull)manager didChangeAuthorizationStatus:(CLAuthorizationStatus)status;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didEnterRegion:(CLRegion * _Nonnull)region;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didExitRegion:(CLRegion * _Nonnull)region;
@end



@class UIImage;

SWIFT_CLASS("_TtC19ProximitisFramework8Campaign")
@interface Campaign : DefaultObject <NSCoding>
@property (nonatomic, copy) NSString * _Nonnull notificationTitle;
@property (nonatomic, copy) NSString * _Nonnull notificationText;
@property (nonatomic, copy) NSString * _Nullable notificationImage;
@property (nonatomic, copy) NSString * _Nonnull type;
@property (nonatomic, copy) NSString * _Nullable detailUrl;
@property (nonatomic, copy) NSString * _Nonnull listImage;
@property (nonatomic, copy) NSString * _Nonnull listTitle;
@property (nonatomic, copy) NSString * _Nonnull listText;
@property (nonatomic) BOOL isActive;
@property (nonatomic, copy) NSString * _Nonnull inAppEvent;
@property (nonatomic) NSInteger cooldown;
@property (nonatomic) NSInteger maximumNotificationsPerUser;
@property (nonatomic, copy) NSDate * _Nonnull created;
@property (nonatomic, copy) NSDate * _Nullable updated;
@property (nonatomic, copy) NSDate * _Nullable notificationSent;
@property (nonatomic) NSInteger notificationCount;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (BOOL)needsUpdate SWIFT_WARN_UNUSED_RESULT;
- (BOOL)shouldNotify SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)listImageName SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)notificationImageName SWIFT_WARN_UNUSED_RESULT;
- (UIImage * _Nullable)image SWIFT_WARN_UNUSED_RESULT;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19ProximitisFramework15CampaignFactory")
@interface CampaignFactory : NSObject
+ (CampaignFactory * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (void)setUpdateWithCampaign:(Campaign * _Nonnull)campaign;
- (void)setNotifiedWithCampaign:(Campaign * _Nonnull)campaign;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19ProximitisFramework15CampaignManager")
@interface CampaignManager : NSObject
+ (void)updateAllCampaignsWithCompletion:(void (^ _Nonnull)(void))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19ProximitisFramework12CustomButton")
@interface CustomButton : UIButton
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC19ProximitisFramework11DetailBlock")
@interface DetailBlock : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19ProximitisFramework18DetailBlockCreator")
@interface DetailBlockCreator : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19ProximitisFramework5Event")
@interface Event : DefaultObject <NSCoding>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19ProximitisFramework12EventFactory")
@interface EventFactory : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC19ProximitisFramework15JSONFileManager")
@interface JSONFileManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC19ProximitisFramework13ObjectManager")
@interface ObjectManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19ProximitisFramework12ObjectParser")
@interface ObjectParser : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class ProximitisDetailViewController;

SWIFT_CLASS("_TtC19ProximitisFramework10Proximitis")
@interface Proximitis : NSObject
+ (void)setDebugging:(BOOL)debug;
- (void)startWith:(NSString * _Nonnull)applicationKey;
+ (NSURL * _Nonnull)proximitisDirectoryURL SWIFT_WARN_UNUSED_RESULT;
+ (NSURL * _Nonnull)documentsDirectoryURL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull applicationKey;)
+ (NSString * _Nonnull)applicationKey SWIFT_WARN_UNUSED_RESULT;
+ (void)logEventsWithCompletion:(void (^ _Nonnull)(void))completion;
+ (void)openCampaignDetailInModalWithCampaignID:(NSString * _Nonnull)campaignID;
+ (void)applicationDidBecomeActive;
+ (void)applicationDidEnterBackground;
+ (ProximitisDetailViewController * _Nullable)makeCampaignDetailViewControllerWithCampaign:(Campaign * _Nonnull)campaign SWIFT_WARN_UNUSED_RESULT;
+ (void)debug:(NSString * _Nonnull)text;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) Proximitis * _Nonnull shared;)
+ (Proximitis * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (void)performBackgroundFetchWithCompletion:(void (^ _Nonnull)(void))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum StatusBarStyle : NSInteger;

SWIFT_CLASS("_TtC19ProximitisFramework20ProximitisAppearance")
@interface ProximitisAppearance : NSObject
+ (void)reloadTheme;
+ (void)setStatusBar:(enum StatusBarStyle)style;
+ (void)setPrimaryColor:(UIColor * _Nonnull)color;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull primaryColor;)
+ (UIColor * _Nonnull)primaryColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setBackgroundColor:(UIColor * _Nonnull)color;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull backgroundColor;)
+ (UIColor * _Nonnull)backgroundColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setTitleColor:(UIColor * _Nonnull)color;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull titleColor;)
+ (UIColor * _Nonnull)titleColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setHeadingColor:(UIColor * _Nonnull)color;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull headingColor;)
+ (UIColor * _Nonnull)headingColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setTextColor:(UIColor * _Nonnull)color;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull textColor;)
+ (UIColor * _Nonnull)textColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setButtonTextColor:(UIColor * _Nonnull)color;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull buttonTextColor;)
+ (UIColor * _Nonnull)buttonTextColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setButtonColor:(UIColor * _Nonnull)color;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull buttonColor;)
+ (UIColor * _Nonnull)buttonColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setSpacing:(double)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) double spacing;)
+ (double)spacing SWIFT_WARN_UNUSED_RESULT;
+ (void)setTitleFontSize:(double)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) double titleFontSize;)
+ (double)titleFontSize SWIFT_WARN_UNUSED_RESULT;
+ (void)setHeadingFontSize:(double)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) double headingFontSize;)
+ (double)headingFontSize SWIFT_WARN_UNUSED_RESULT;
+ (void)setTextFontSize:(double)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) double textFontSize;)
+ (double)textFontSize SWIFT_WARN_UNUSED_RESULT;
+ (void)setLineHeight:(CGFloat)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat lineHeight;)
+ (CGFloat)lineHeight SWIFT_WARN_UNUSED_RESULT;
+ (void)setDismissButtonImage:(UIImage * _Nonnull)image;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIImage * _Nullable dismissButtonImage;)
+ (UIImage * _Nullable)dismissButtonImage SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19ProximitisFramework22ProximitisConfigurator")
@interface ProximitisConfigurator : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSBundle;

SWIFT_CLASS("_TtC19ProximitisFramework31ProximitisDefaultViewController")
@interface ProximitisDefaultViewController : UIViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIView;

SWIFT_PROTOCOL("_TtP19ProximitisFramework16ProximitisDetail_")
@protocol ProximitisDetail
- (UIView * _Nonnull)viewForTitleWithBlock:(DetailBlock * _Nonnull)block SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)viewForHeadingWithBlock:(DetailBlock * _Nonnull)block SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)viewForParagraphWithBlock:(DetailBlock * _Nonnull)block SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)viewForImageWithBlock:(DetailBlock * _Nonnull)block SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)viewForOrderedListWithBlock:(DetailBlock * _Nonnull)block SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)viewForUnorderedListWithBlock:(DetailBlock * _Nonnull)block SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)viewForButtonWithBlock:(DetailBlock * _Nonnull)block SWIFT_WARN_UNUSED_RESULT;
@optional
- (UIView * _Nonnull)viewForCustomWithBlock:(DetailBlock * _Nonnull)block SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC19ProximitisFramework30ProximitisDetailViewController")
@interface ProximitisDetailViewController : ProximitisDefaultViewController
@property (nonatomic, strong) Campaign * _Nullable campaign;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19ProximitisFramework18ProximitisInfoView")
@interface ProximitisInfoView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithOffset:(CGFloat)offset image:(UIImage * _Nullable)image text:(NSString * _Nullable)text OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class UITableView;
@class UITableViewCell;

SWIFT_CLASS("_TtC19ProximitisFramework28ProximitisListViewController")
@interface ProximitisListViewController : UITableViewController
@property (nonatomic, copy) NSArray<Campaign *> * _Nullable campaigns;
@property (nonatomic) enum UITableViewCellSeparatorStyle separatorStyle;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)openWithCampaign:(Campaign * _Nonnull)campaign;
- (nonnull instancetype)initWithStyle:(UITableViewStyle)style OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19ProximitisFramework34ProximitisNavigationViewController")
@interface ProximitisNavigationViewController : UINavigationController
- (void)viewDidLoad;
- (void)addDismissButton;
- (void)close;
- (nonnull instancetype)initWithNavigationBarClass:(Class _Nullable)navigationBarClass toolbarClass:(Class _Nullable)toolbarClass OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=5.0);
- (nonnull instancetype)initWithRootViewController:(UIViewController * _Nonnull)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UNNotificationResponse;

SWIFT_CLASS("_TtC19ProximitisFramework28ProximitisNotificationClient")
@interface ProximitisNotificationClient : NSObject
- (void)scheduleNotificationFor:(Campaign * _Nonnull)campaign;
+ (void)notificationTappedWithResponse:(UNNotificationResponse * _Nonnull)response;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSAttributedString;
@class UILabel;

SWIFT_CLASS("_TtC19ProximitisFramework28ProximitisPageViewController")
@interface ProximitisPageViewController : ProximitisDetailViewController
@property (nonatomic, copy) NSArray<UIView *> * _Nonnull views;
@property (nonatomic, copy) NSArray<DetailBlock *> * _Nullable blocks;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)addWithBlockView:(UIView * _Nonnull)blockView;
- (UILabel * _Nonnull)attributedLabelWithText:(NSAttributedString * _Nonnull)text SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface ProximitisPageViewController (SWIFT_EXTENSION(ProximitisFramework)) <ProximitisDetail>
- (UIView * _Nonnull)viewForTitleWithBlock:(DetailBlock * _Nonnull)block SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)viewForHeadingWithBlock:(DetailBlock * _Nonnull)block SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)viewForParagraphWithBlock:(DetailBlock * _Nonnull)block SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)viewForImageWithBlock:(DetailBlock * _Nonnull)block SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)viewForOrderedListWithBlock:(DetailBlock * _Nonnull)block SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)viewForUnorderedListWithBlock:(DetailBlock * _Nonnull)block SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)viewForButtonWithBlock:(DetailBlock * _Nonnull)block SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)viewForCustomWithBlock:(DetailBlock * _Nonnull)block SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC19ProximitisFramework27ProximitisWebViewController")
@interface ProximitisWebViewController : ProximitisDetailViewController
@property (nonatomic, strong) UIView * _Null_unspecified infoScreen;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class WKWebView;
@class WKNavigation;

@interface ProximitisWebViewController (SWIFT_EXTENSION(ProximitisFramework)) <WKNavigationDelegate>
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
@end

typedef SWIFT_ENUM(NSInteger, StatusBarStyle, closed) {
  StatusBarStyleLight = 0,
  StatusBarStyleDark = 1,
};


/// A class that takes a <a href="https://daringfireball.net/projects/markdown/">Markdown</a> string or file and returns an NSAttributedString with the applied styles. Supports Dynamic Type.
SWIFT_CLASS("_TtC19ProximitisFramework14SwiftyMarkdown")
@interface SwiftyMarkdown : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end











#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
